### ISSUE TITLE
horizontal scroll bar intersects typing indictator

### ISSUE THREAD

**Issue by Maximal98** [uowuo/abaddon#117]
what i think is a vertical scrollbar is intersecting the writing indicator on the newest build from git atm ([commit](https://github.com/uowuo/abaddon/commit/64245bf7457a81eed063901ad8e5ce55fdc2ca0c))

![epical bug](https://user-images.githubusercontent.com/55159959/198904870-0fa0268e-63c4-48e1-a066-6e36ccde4218.png)

**Comment by ouwou** [comment]
im pretty sure thats the attachment upload progress bar. have you changed the css at all?

**Comment by Maximal98** [comment]
sorry for the late response! i havent modified the css but i did add a hacky patch to remove the member list entirely because temporary solutions are the most permanent solutions, so that might be that cause. gonna check in a bit

**Comment by ouwou** [comment]
i dont really know why it would be visible at all since it styled to be transparent unless theres upload progress. member list shouldnt have anything to do with it (btw you can CTRL+M it away on master now). if you want to double check what it is you can try launching with `GTK_DEBUG=interactive` as environment var

**Comment by ouwou** [comment]
css has been significantly changed and progress bar is hidden unless active. can be reopened if still an issue though i plan on moving the progress bar somewhere else
