### ISSUE TITLE
Option to hide the member list consitently

### ISSUE THREAD

**Issue by Maximal98** [uowuo/abaddon#118]
Currently the only way of hiding the member list is pushing it into the side, which resets every time abaddon starts up, i think it would be nice to have it work like the alt menu.

**Comment by ouwou** [comment]
i added menu items and shortcuts (ctrl+L ctrl+M) so its easier to hide them (yet to commit), but because currently state is tied to a particular discord user i cant keep the visibility state across sessions. would that still suffice for the sake of this issue? if not i could try to add some sort of "global" state that isnt user specific

**Comment by ouwou** [comment]
i didnt make it preserve the state across instances since its a bit more challenging (tell me if ur still interested in that), but the latest commit should hopefully make it more convenient

**Comment by Maximal98** [comment]
yeah that's alright as well. also it could be possible to add a setting in the config to not display it outright.
