### ISSUE TITLE
token not being saved (or abaddon not reading ini file)

### ISSUE THREAD

**Issue by vannotz** [uowuo/abaddon#146]
Hi, whenever I launch abaddon it does not automatically open my discord account, I have my token set in _~/.config/abaddon/abaddon.ini_ as:
```
[discord]
token = mytoken
autoconnect = true
```
But whenever I open abaddon I have to set my token and click connect again.
When I run abaddon in a terminal window I get the following errors:
```
keychain error setting token: The name org.freedesktop.secrets was not provided by any .service files
keychain error reading token: The name org.freedesktop.secrets was not provided by any .service files (2)
```
and when I close it I get some more:
```
Unknown event SESSIONS_REPLACE
got socket close code: 1000
keychain error setting token: The name org.freedesktop.secrets was not provided by any .service files
```
This _might?_ have something to do with the fact that I'm running runit as my init system instead of systemd on Artix Linux, socket errors aren't too unfamiliar to me, which is what got me running [socklog](http://smarden.org/socklog/), but I'm not sure my init system is exactly the error.
Besides that everything works fantastically, you people did a very good job!

**Comment by ouwou** [comment]
you need something that supports the secret service api/libsecret like gnome-keyring or kwallet.
alternatively you can compile with `-DUSE_KEYCHAIN=OFF` passed to cmake and it will store it in plaintext.
your token disappears because its trying to convert it from plaintext .ini to nice and safe in the keyring but that fails so it looks like its just deleting it for no reason

**Comment by vannotz** [comment]
tried using gnome-keyring and it worked, thank you for the help

**Comment by DUOLabs333** [comment]
I have kwallet installed, but I still have the same problem.
