### ISSUE TITLE
Emoji inserting popup's background is white

### ISSUE THREAD

**Issue by hawl1** [uowuo/abaddon#198]
![emojii](https://github.com/uowuo/abaddon/assets/126889064/75e04ae9-1638-4821-92dc-88e3be9df9e8)

**Comment by TheMorc** [comment]
same thing currently happens on macOS too and it also doesn't render emojis. as for emojis, that's not a problem with abaddon since gtk3-demo has the same issue. My guess is that GTK is still running in light mode (and that can be tested when you rip the css folder from abaddon and run it)

<img width="431" alt="image" src="https://github.com/uowuo/abaddon/assets/13377926/8c50b0ff-7580-45c0-9543-af88968e9734">

**Comment by TheMorc** [comment]
running abaddon with the dark adwaita theme using this `GTK_THEME=Adwaita:dark` environment variable fixes the issue as I hoped

<img width="423" alt="image" src="https://github.com/uowuo/abaddon/assets/13377926/2642f247-7f9c-4eef-a409-97d8734b9aa4">

no luck on those emojis, but that's a different issue

**Comment by ouwou** [comment]
the emoji picker is part of GTK. ill probably add some styling in the default css file but eventually hopefully ill write my own emoji picker and disable the builtin one
