### ISSUE TITLE
Excessive CPU usage even during idle periods

### ISSUE THREAD

**Issue by brokiem** [uowuo/abaddon#202]
Abaddon consistently utilizes around 30% of the CPU even when it's not performing any tasks. I tried to wait for a while, but it was still using about 30% of the CPU resources on my Intel Core i5-2400. This is quite annoying, especially when the official client, which runs on Electron, only utilizes less than 2% of the CPU when it's idle.

## Steps
1. Download Abaddon from the release page (https://github.com/uowuo/abaddon/releases/tag/v0.1.11)
2. Locate and run the "abaddon.exe" executable file.
3. After launching Abaddon, monitor your CPU usage, in my case it hovers around 30%.

## Image
![image](https://github.com/uowuo/abaddon/assets/61258338/efa3ce2a-f79a-4bf4-bb40-c4e91d5739ca)

**Comment by ouwou** [comment]
it should definitely be 0.0% if you just opened it and its idle. this is probably unlikely, but maybe you have an old version of something its picking up instead of using the dlls in the zip. try launching from the command prompt by doing `set PATH=` and then `abaddon.exe`. if that doesnt work, then i would try attaching gdb and seeing what its spending so much CPU time doing. if you dont know how to do that drop a message in the discord cuz itll probably take a bit of back and forth

**Comment by brokiem** [comment]
Hi, I just downloaded the latest build from github artifact, and it seems to run smoothly (CPU usage 0%). I think the problem was on my end. Thanks for the quick response!
