### ISSUE TITLE
[Feature request] no automatic light/dark mode switching

### ISSUE THREAD

**Issue by TheMorc** [uowuo/abaddon#211]
I didn't take a look at gtk3 properly as if it supports automatic light/dark mode switching on macOS (or maybe also Linux)
Introducing it would bring a small issue where the css is currently only for one theme style and isn't duplicated to have a light mode or doesn't dynamically change somehow.

same could be applied for windows theme switching and it could probably fix the white titlebar too?

**Comment by ouwou** [comment]
i made the (perhaps stupid) decision to basically try and trample over whatever the system theme is to get everything to look nice cuz im a filthy windows user and didnt really know what i was doing. so that being said i guess the real issue here would be trying to respect the system theme. afaik on linux thats how dark vs light mode would be implemented too (e.g. you have Adwaita and Adwaita:dark as a variant). and iirc if the system theme switches then GTK applications automatically are able to pick that up.

**Comment by aaronliu0130** [comment]
What's the status of system theme support?

**Comment by ouwou** [comment]
well, i think "automatic light/dark mode switching" is probably a system thing and not a me thing so ill close this. but as for respecting the system theme in general, maybe you/someone can open an issue about that. i expect itll take some back and forth to figure it out since i dont use gnome/any environment where gtk themes really exist
