### ISSUE TITLE
[bug] "Unknown event CHANNEL_UNREAD-UPDATE"

### ISSUE THREAD

**Issue by tawnylure** [uowuo/abaddon#225]
Seems to be unable to call for channel updates, possible reason why you have to manually mark a channel read if you're in it to get rid of the notification.

**Comment by ouwou** [comment]
`CHANNEL_UNREAD_UPDATE` isnt handled since its basically useless. its safe to ignore that message. it is kinda spammy though so maybe ill add a handler just to get it to go away.

the need to mark a channel as read if youre in it is a separate issue. if you want you can open another issue about that but either way ill probably fix it tomorrow hopefully maybe probably
