### ISSUE TITLE
"Build number could not be fetched" block load abaddon.ini

### ISSUE THREAD

**Issue by mattthhh** [uowuo/abaddon#251]
When I start the app, I get the prompt window in the title, if I close it I can still use the app, but I need to add my token manually and connect manually too. Then it doesn't read my .config/abaddon/abaddon.ini file. Is there a way to correct that ?

**Comment by ouwou** [comment]
ok i think this is two different issues

"build number couldnt be fetched" - can you try a build from master?
"i need to add my token manually" - do you mean when you set your token, it doesnt stay across restarts? in this case you need a keyring service like gnome-keyring. alternatively you can compile with `-DUSE_KEYCHAIN=OFF` and it will store your token in the .ini

**Comment by mattthhh** [comment]
> ok i think this is two different issues
> 
> "build number couldnt be fetched" - can you try a build from master? 

I installed this with the AUR repo, so idk if it compiles it or it takes the binary.

> "i need to add my token manually" - do you mean when you set your token, it doesnt stay across restarts? in this case you need a keyring service like gnome-keyring. 
> alternatively you can compile with `-DUSE_KEYCHAIN=OFF` and it will store your token in the .ini

The problem is that i set my token in the .ini, and I have other settings in the file, but abaddon after showing the prompt don't take any of my config file. So it doesn't really matter if i use gnome-keyring or not I guess...

**Comment by ouwou** [comment]
> I installed this with the AUR repo

abaddon is latest release, abaddon-git is latest master. either way the build number thing is probably worth making a new release for so i might do that later today

> The problem is that i set my token in the .ini

if you compile with keyring support, abaddon will remove the token and try to save it in the keychain. so if the token is deleted that means the config is being used. if the token isnt being removed/your sure the .ini isnt being read, check to make sure there isnt an `abaddon.ini` in your cwd/next to the executable since that will take higher precedence

**Comment by mattthhh** [comment]
Okay, with a keyring system, the token is actually stored and i don't need to insert it each time. But it stills doesn't auto-connect, and i think thats because i get the prompt

**Comment by ouwou** [comment]
made a new release with the build number fix. let me know if theres still any issues after an update
