### ISSUE TITLE
Frequent disconnects with no automatic reconnect, suggest auto-reconnect with exp. backoff

### ISSUE THREAD

**Issue by NexAdn** [uowuo/abaddon#31]
So, running abaddon for a few days now, I've noticed that sometimes the gateway connection gets closed. While this is a normal side-effect of having connections over the Internet, this gets annoying if I manually have to re-connect every time this happens. And, unfortunately, this sometimes happens several times in a few hours (which is a bit too much for my very stable network connection, but I think this is just the Discord server initiating a disconnect rather than the transport networks' effects).

I suggest automatic reconnects with something like an exponential backoff in case the disconnects happen more frequently. Ideal would be to have a behavior similar to the Discord web application, but since we don't know for sure how that one behaves, we can just assume the behavior. And usually, exponential backoff is a good tradeoff between having fast reconnects when it's possible (i.e. when the disconnects happen for a minor reason, like getting a new IPv4 address) and not flooding the network/server with reconnection attempts when the network/server doesn't allow a reconnect. This could be implemented in the hope that it doesn't make the Discord server suspicious of us having a custom client and still allowing fast automatic reconnects where applicable.

**Comment by ouwou** [comment]
i think the disconnecting is Discord's resume mechanism where it tells the client to reconnect by itself and closes the socket a couple minutes after. that's something that should be handled already but perhaps something broke since i last tested it. do you get a dialog window with the close code? (IIRC the resume-related disconnect should give close code 1011) either way i'll see if i can figure out what's going on here

**Comment by NexAdn** [comment]
I've got a disconnect a few minutes ago with the following message:

```
Lost connection with Discord's gateway. Try reconnecting (code 1006)
```

**Comment by ouwou** [comment]
> 
> 
> I've got a disconnect a few minutes ago with the following message:
> 
> ```
> Lost connection with Discord's gateway. Try reconnecting (code 1006)
> ```

yeah i think 1006 is what would happen after a failed resume. i don't think it's a problem with responding to the reconnect message but something else maybe related. i've only had it occur once after running all day but i forgot to log the socket messages :P i'll keep looking into it

**Comment by ouwou** [comment]
it should try to resume and re-identify now. i limited it to the code 1006 since i've only seen it happen with 1006 and i haven't added any backoff or something to stop a loop (shouldn't cause any issues even if it loops though). i am curious on if it will successfully resume or if it requires a re-identify for you though. you can tell it's a re-identify because the channel list and member list will empty out and re-populate unlike a resume and it will also say so in stdout. let me know what happens :^)

as for the backoff idea i feel like it would be better to re-attempt it only a couple times at most rather than try repeatedly since if it fails to reconnect more than once there's probably something wrong. and also because a looping reconnect seems like it would be weird UI/UX-wise

**Comment by NexAdn** [comment]
I've used abaddon with the fix for some time now and I didn't notice any major issue (I had a small disconnect some time ago). Overall, the new reconnect mechanism works even across IP address changes and multiple hours of my laptop being in suspend. So I'd consider this fix being stable enough
