### ISSUE TITLE
Support for saving the application state

### ISSUE THREAD

**Issue by NexAdn** [uowuo/abaddon#36]
It's a bit annoying that every time I start abaddon, I have to re-open the chats I had opened last time and collapse categories I had collapsed last time.

Thus, I'd really love to see abaddon cache some parts of the application state across application startups. This could e.g. be just done in a file inside `~/.cache/`. I honestly don't know where most applications save such a state, but the cache directory is definitely not the wrong place, although settings might get lost when the cache gets cleared (which some people do manually, if the cache directory becomes too big).

**Comment by ouwou** [comment]
the channel you last had opened and the expansion state should be saved now. lemme know if you notice anything worth changing. also i noticed immediately after pushing when i came to reply the relatively new base directory `XDG_STATE_HOME` (`~/.local/state`) which seems like exactly what i should be using instead of `~/.cache/` lol. i'm still not sure if i like the way i implemented this so i'll keep this issue open for a bit probably

**Comment by NexAdn** [comment]
can confirm that it keeps the channels opened, thanks!

**Comment by ouwou** [comment]
only thing i might change is the directory it saves the state, but everything seems to work either way so ill close
