### ISSUE TITLE
Failed to save token in settings file

### ISSUE THREAD

**Issue by Zander671** [uowuo/abaddon#52]
Hi, I am on ArchLinux with the newest version of abaddon installed using the "abbadon-git" package. When I close abbadon, I get this message "failed to save settings KeyFile: Failed to create file “./abaddon.ini.91VJE1”: Permission denied". The symptom of this is that I am unable to set my token from the UI.

**Comment by javsanpar** [comment]
You are right, I also have this problem.

I must do a new version of the package, changing `/opt/abaddon/abaddon.ini` permissions. Or try to use move the config file to the user folder.

**Comment by javsanpar** [comment]
I have been thinking about which should create the user config file.

Abaddon's execution should create `~/.config/abaddon/abaddon.ini` if it not exists. It does not make sense for the package to create a config files for each user in the machine. Users created after package installation will not have the config file.

What do you think @ouwou and @NexAdn?

**Comment by NexAdn** [comment]
> Abaddon's execution should create ~/.config/abaddon/abaddon.ini if it not exists.

Definitely! Under no circumstance should a software depend on the currently existing users nor create files in their directories at build/install time. Stuff that happens in a user's home has to happen at runtine only and the software should be able to run with a completely empty home.

**Comment by NexAdn** [comment]
@javsanpar I suggest a workaround: Move the abaddon binary to `/usr/lib/abaddon` and install a wrapper script in `/usr/bin`, which creates `~/.config/abaddon/abaddon.ini` (and, if required, all parent directories) if it doesn't exist and then just runs `exec /usr/lib/abaddon/abaddon`.

I did a similar thing to make abaddon work under Gentoo before it had support for a config file in `~/.config`.

**Comment by javsanpar** [comment]
Thank you for the suggestion and the examples!

How are you now dealing with the creation of the config file if abaddon does not create it at run time, and you are not using anymore the wrapper script?

**Comment by NexAdn** [comment]
Well, I wasn't aware of the issue with creating the files, since everything worked after the workaround and removing the wrapper didn't cause any failure.

Anyway, a wrapper script isn't really necessary on Gentoo. I just confirmed that abaddon-0.1.2 and the git version has no problem saving a config file. However, it saves it in `pwd`, not `~/.config/abaddon/abaddon.ini`.

So it seems more like upstream isn't the problem here, but rather something downstream. Maybe re-check the packaging process. Anyway, this is nothing that is to be discussed in upstream's GitHub.

The only issue that remains for upstream is that abaddon creates the config file in pwd and not `~/.config/abaddon/abaddon.ini` (possibly creating any necessary parent directories).

**Comment by ouwou** [comment]
since the problem is just the fallback location, ill change it so that if the ini isnt found the default location will write to `~/.config/abaddon/abaddon.ini` and make the directories

**Comment by ouwou** [comment]
i think that should take care of it lemme know if anything else needs changing

**Comment by Zander671** [comment]
That fixed it!

**Comment by dertuxmalwieder** [comment]
> since the problem is just the fallback location, ill change it so that if the ini isnt found the default location will write to `~/.config/abaddon/abaddon.ini` and make the directories

On macOS, it does not. In fact, it entirely ignores the file.
