### ISSUE TITLE
Failing to compile on Debian Linux

### ISSUE THREAD

**Issue by shampee** [uowuo/abaddon#68]
I've installed libgtkmm-3.0-dev, libcurl4-gnutls-dev, and nlohmann-json and `git clone --recurse-submodules="subprojects" https://github.com/uowuo/abaddon && cd abaddon
mkdir build && cd build && cmake .. && make` gives me:
```
[100%] Linking CXX executable abaddon
/bin/ld: /usr/local/lib/libixwebsocket.a(IXGzipCodec.cpp.o): in function `ix::gzipCompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
IXGzipCodec.cpp:(.text+0x1e): undefined reference to `libdeflate_alloc_compressor'
/bin/ld: IXGzipCodec.cpp:(.text+0x55): undefined reference to `libdeflate_gzip_compress_bound'
/bin/ld: IXGzipCodec.cpp:(.text+0xa0): undefined reference to `libdeflate_gzip_compress'
/bin/ld: IXGzipCodec.cpp:(.text+0xb0): undefined reference to `libdeflate_free_compressor'
/bin/ld: /usr/local/lib/libixwebsocket.a(IXGzipCodec.cpp.o): in function `ix::gzipDecompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
IXGzipCodec.cpp:(.text+0x1a8): undefined reference to `libdeflate_alloc_decompressor'
/bin/ld: IXGzipCodec.cpp:(.text+0x237): undefined reference to `libdeflate_gzip_decompress'
/bin/ld: IXGzipCodec.cpp:(.text+0x246): undefined reference to `libdeflate_free_decompressor'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/abaddon.dir/build.make:1225: abaddon] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/abaddon.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
Seems like ixwebsocket has trouble finding libdeflate. I've tried adding `-ldeflate` in various parts of the code but it hasn't helped.

**Comment by ouwou** [comment]
can you try checking out subprojects/ixwebsocket to the latest release? the commit is machinezone/IXWebSocket@2f560ff4c07e5446f2539505cb4f64f80b54ca8e. it will probably give you a different error telling you to install zlib, or perhaps you can try installing zlib without updating the submodule and see if it works, since deflate is a fallback if zlib isnt found

**Comment by shampee** [comment]
I have the zlib1g + zlib1g-dev (version 1:1.2.11) and libdeflate + libdeflate-dev (version 1.10-2) packages installed. I checked out https://github.com/machinezone/IXWebSocket/commit/2f560ff4c07e5446f2539505cb4f64f80b54ca8e and tried cmaking and making again but still got the same error messages. Checking out https://github.com/machinezone/IXWebSocket/commit/e8048ad82610647bf49b9876d9eff4d889bf1177 and building again also gave me the same result.

**Comment by ouwou** [comment]
i dont see how you could get the same error since that part of the code shouldnt even be compiled unless you manually set [USE_ZLIB](https://github.com/machinezone/IXWebSocket/blob/master/CMakeLists.txt#L235-L242) to false. maybe the old settings are cached? you can probably just add `-DUSE_ZLIB=ON` or clear the cache

**Comment by ouwou** [comment]
you can reopen if you still want me to try and help, but im pretty sure if you do a clean build and make sure zlib is installed and found you shouldnt get this
